env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - 'react-hooks'
  - prettier
  - 'simple-import-sort'
ignorePatterns: 
  - "dist"
rules: {}
settings: {
  'import/resolver' : {
    typescript: {}
  }
}